<?php

    class MapTest extends PHPUnit\Framework\TestCase
    {

        public function setUp()
        {
            //setup
        }


        /**
         * @dataProvider providerPath
         */
        public function testHexa($x, $y, $teams, $terrains)
        {
            ob_start();
            $map = new \xtodx\MapGenerator\Map($x, $y, $teams);
            $map->setTerrains($terrains);
            $map->generateTerrain();
            $map->generateLimitUnits();
            $map->generateUnits();
            $matrix = $map->getTerrain();
            $this->assertTrue(true, $matrix);
            ob_end_clean();
        }

        public function providerPath()
        {
            return [
                "okay" => [
                    10,
                    10,
                    2,
                    ["Water", "Mountains", "Swamp", "Grass", "Forest"]
                ],
                "easy" => [
                    10,
                    10,
                    2,
                    ["Water", "Grass"]
                ],
                "big" => [
                    2,
                    4,
                    5,
                    ["Water", "Mountains", "Swamp", "Grass", "Forest"]
                ],
                "noterrain" => [
                    2,
                    4,
                    5,
                    ["Water", "Mountains", "Swamp", "Grass", "Forest", "Noterrain"]
                ],
                "hard" => [
                    200,
                    200,
                    30,
                    ["Water", "Mountains", "Swamp", "Grass", "Forest"]
                ],
            ];
        }

        public function tearDown()/* The :void return type declaration that should be here would cause a BC issue */
        {
            parent::tearDown(); // TODO: Change the autogenerated stub
        }
    }